# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FR_get_output <- function() {
    .Call('_funfit_FR_get_output', PACKAGE = 'funfit')
}

FR_set_state <- function(new_state) {
    invisible(.Call('_funfit_FR_set_state', PACKAGE = 'funfit', new_state))
}

FR_get_state <- function() {
    .Call('_funfit_FR_get_state', PACKAGE = 'funfit')
}

FR_reset_observer <- function() {
    invisible(.Call('_funfit_FR_reset_observer', PACKAGE = 'funfit'))
}

FR_adap <- function(init, duration, step_size = 1.0, start = 0.0) {
    .Call('_funfit_FR_adap', PACKAGE = 'funfit', init, duration, step_size, start)
}

FR_at <- function(init, times, step_size = 1.0, start = 0.0) {
    .Call('_funfit_FR_at', PACKAGE = 'funfit', init, times, step_size, start)
}

FR_continue_at <- function(times, step_size = 1.0) {
    .Call('_funfit_FR_continue_at', PACKAGE = 'funfit', times, step_size)
}

FR <- function(init, duration, step_size = 1.0, start = 0.0) {
    .Call('_funfit_FR', PACKAGE = 'funfit', init, duration, step_size, start)
}

FR_no_record <- function(init, duration, step_size = 1.0, start = 0.0) {
    .Call('_funfit_FR_no_record', PACKAGE = 'funfit', init, duration, step_size, start)
}

FR_set_params <- function(Fmax, N0, h, P) {
    invisible(.Call('_funfit_FR_set_params', PACKAGE = 'funfit', Fmax, N0, h, P))
}

FR_get_params <- function() {
    .Call('_funfit_FR_get_params', PACKAGE = 'funfit')
}

